version: "3"

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: NANode
    ports:
    - "8081:8080"
    volumes:
    - .:/user/src/app/
    - /user/src/app/node_modules/
  cockroach:
    image: lovohh/cockroach_usdadb:nutriapp
    container_name: NAACockroach
    ports:
    - "26257:26257"
    - "8080:8080"
