version: "3"

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: NANode
    ports:
      - "8080:8080"
    volumes:
      - .:/user/src/app/
      - /user/src/app/node_modules/